#!/usr/bin/env bash
# Regenerates compile_commands.json for clangd (nvim).
# STM32CubeIDE remains the real build system; this only feeds the editor index.
# Re-run after adding new .c files or new include directories.
# Flags mirror Debug/*/subdir.mk as generated by CubeIDE.
set -euo pipefail
cd "$(dirname "$0")"
ROOT="$PWD"

GCC=$(find /Applications/STM32CubeIDE.app -name arm-none-eabi-gcc 2>/dev/null | head -1)
[ -n "$GCC" ] || { echo "arm-none-eabi-gcc not found in STM32CubeIDE.app" >&2; exit 1; }

FLAGS="-mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -std=gnu11 \
-DDEBUG -DUSE_HAL_DRIVER -DSTM32F407xx -DSTM32_THREAD_SAFE_STRATEGY=4"

for inc in Core/Inc Core/ThreadSafe Apps/Inc PeripheralDrivers/Inc Tests/Inc \
           Drivers/STM32F4xx_HAL_Driver/Inc Drivers/STM32F4xx_HAL_Driver/Inc/Legacy \
           Drivers/CMSIS/Device/ST/STM32F4xx/Include Drivers/CMSIS/Include \
           Middlewares/Third_Party/FreeRTOS/Source/include \
           Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
           Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F; do
  FLAGS="$FLAGS -I$ROOT/$inc"
done

{
  echo "["
  first=1
  while IFS= read -r f; do
    [ $first -eq 1 ] || echo ","
    first=0
    printf '  {"directory": "%s", "file": "%s", "command": "%s %s -c %s"}' \
      "$ROOT" "$ROOT/$f" "$GCC" "$FLAGS" "$ROOT/$f"
  done < <(find Core Apps PeripheralDrivers Tests Drivers Middlewares \
             -name '*.c' -not -path '*/Debug/*' | sort)
  echo ""
  echo "]"
} > compile_commands.json

echo "compile_commands.json: $(grep -c '"file"' compile_commands.json) entries"
